version: 1
disable_existing_loggers: False

formatters:
    simple:
        format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
        datefmt: '%Y-%m-%d %H:%M:%S'

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout

  file:
    class: logging.FileHandler
    level: INFO
    formatter: simple
    filename: myapp.log
    mode: a
  
  rich:
    class: rich.logging.RichHandler
    level: INFO

    
loggers:
  "": # root logger
    level: DEBUG
    handlers: [rich]
    propagate: true

